### ISSUE TITLE
Question: Does this support native bindings for core-ml stuff?

### ISSUE THREAD

**Issue by CestDiego** [xenodium/EmacsMacOSModule#2]
Given latest wwdc announcement it would be amazing to create a module that would use the “Apple Intelligence” features that run locally to rewrite and even export app intents to the local first Siri assistants.

**Comment by xenodium** [comment]
I don't see why not, but there's only one way to find out... PR's welcome ;)

**Comment by CestDiego** [comment]
Thanks for the quick response. I'm starting to play with this but the macOS share is crashing Emacs. https://github.com/SavchenkoValeriy/emacs-swift-module/issues/36 I opened a bug here by mistake 😓  but I'm trying to actively debug this. Since you are the owner of this package, do you see something wrong in my crash dump? I'm new to swift but I just pulled the repo and ran it so I'm surprised. I'm using Monterrey.

**Comment by xenodium** [comment]
> I'm using Monterrey.

https://pastebin.com/XDCQQwsk reports `macOS 14.5`?

I was on 14.1, so I upgraded to 14.5 to see if I could reproduce. Still OK here after rebuilding w/ `M-x macos-module-dev-reload` and running `M-x macos-share`.

Could you share more details about how you installed and ran things?

**Comment by xenodium** [comment]
It's been a while since the last interaction. Gonna go ahead and close, please reopen if needed.
